// typescript/rest-nextjs-api-routes-auth/pages/index.tsx
import React from 'react'
import { GetServerSideProps } from 'next'
import Layout from '../components/Layout'
import Post, { PostProps } from '../components/Post'

type Props = {
  feed: PostProps[]
}

const Blog : React.FC<Props> = props => {
  return (
    <Layout>
      <div className="page">
        <h1>Public Feed</h1>
        <main>
          {props.feed.map(post => (
            <div key={post.id} className="post">
              <Post post={post} />
            </div>
          ))}
        </main>
      </div>
      <style jsx>{`
        .post {
          background: white;
          transition: box-shadow 0.1s ease-in;
        }

        .post:hover {
          box-shadow: 1px 1px 3px #aaa;
        }

        .post + .post {
          margin-top: 2rem;
        }
      `}</style>
    </Layout>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('http://localhost:3000/api/feed')
  const feed = await res.json()
  return {
    props: { feed },
  }
}

export default Blog

// javascript/rest-nuxtjs/pages/index.vue
<template>
  <div class="page">
    <h1>My Blog</h1>
    <main>
      <p v-if="$fetchState.pending">
        <span class="loading"></span>
      </p>
      <p v-else-if="$fetchState.error">Error while fetching feed 💔</p>
      <div v-else>
        <Post class="post" v-for="post in feed" :key="post.id" :post="post" />
      </div>
    </main>
  </div>
</template>

<script>
import Post from '@/components/Post'
export default {
  components: { Post },
  data() {
    return {
      feed: [],
    }
  },
  async fetch() {
    const feed = await fetch(`http://localhost:3000/api/feed`).then((res) =>
      res.json()
    )
    this.feed = feed
  },
}
</script>

<style>
.post {
  background: white;
  transition: box-shadow 0.1s ease-in;
}

.post:hover {
  box-shadow: 1px 1px 3px #aaa;
}

.post,
.post {
  margin-top: 2rem;
}
</style>
