// javascript/rest-nuxtjs/pages/drafts.vue
<template>
  <div class="page">
    <h1>Drafts</h1>
    <main>
      <p v-if="pending">
        <span class="loading"></span>
      </p>
      <p v-else-if="error">Error while fetching drafts 💔</p>
      <div v-else>
        <Post class="post" v-for="post in drafts" :key="post.id" :post="post" />
      </div>
    </main>
  </div>
</template>
<script setup>

const { data: drafts, error, pending } = await useFetch('/api/drafts')

</script>
<style scoped>
.post {
  background: white;
  transition: box-shadow 0.1s ease-in;
}

.post:hover {
  box-shadow: 1px 1px 3px #aaa;
}

.post+.post {
  margin-top: 2rem;
}
</style>

// orm/nextjs-trpc/src/pages/drafts.tsx
import Layout from "../components/Layout"
import Post from "../components/Post"
import { api } from "../utils/api"

const Drafts = () => {
  const { data } = api.post.drafts.useQuery()
  return (
    <Layout>
      <div className="page">
        <h1>Drafts</h1>
        <main>
          {data?.map((post) => (
            <div key={post.id} className="post">
              <Post post={post} />
            </div>
          ))}
        </main>
      </div>
      <style jsx>{`
        .post {
          background: white;
          transition: box-shadow 0.1s ease-in;
        }

        .post:hover {
          box-shadow: 1px 1px 3px #aaa;
        }

        .post + .post {
          margin-top: 2rem;
        }
      `}</style>
    </Layout>
  )
}

export default Drafts
