// prisma-postgres/nextjs-starter/components/Quote/QuoteWrapper.tsx
import { QuoteCacheType } from "@/lib/types";
import { ReactNode } from "react";

export const QuoteWrapper: React.FC<{
  title: string;
  type: QuoteCacheType;
  children: ReactNode;
}> = ({ title, type, children }) => {
  return (
    <div className="w-full h-full bg-white border border-gray-200 rounded-lg shadow p-4 dark:bg-gray-800 dark:border-gray-700">
      <div className="flex items-center justify-between">
        <h5 className="text-xl font-bold leading-none text-gray-900 dark:text-white">
          {title}
        </h5>
        <div className="w-16"></div>
        <p className="text-xl font-medium text-blue-600 dark:text-blue-500">
          {type}
        </p>
      </div>
      <div>{children}</div>
    </div>
  );
};

// accelerate/solidstart-starter/src/components/quoteWrapper.tsx
import { Component, JSX } from 'solid-js';

type QuoteWrapperProps = {
  title: string;
  type: string;
  children: JSX.Element;
};

const QuoteWrapper: Component<QuoteWrapperProps> = ({ title, type, children }) => {
  return (
    <div class="quote-wrapper border p-4 rounded-lg shadow-md">
      <h2 class="text-xl font-bold mb-2">{title}</h2>
      <p class="text-gray-700 mb-4">Type: {type}</p>
      {children}
    </div>
  );
};

export default QuoteWrapper;
