// javascript/rest-nextjs/components/Post.jsx
import Link from 'next/link'
import ReactMarkdown from 'react-markdown'

const Post = ({ post }) => {
  const authorName = post.author ? post.author.name : 'Unknown author'
  return (
    <Link href="/p/[id]" as={`/p/${post.id}`}>
      <a>
        <h2>{post.title}</h2>
        <small>By {authorName}</small>
        <ReactMarkdown source={post.content} />
        <style jsx>{`
          a {
            text-decoration: none;
            color: inherit;
            padding: 2rem;
            display: block;
          }
        `}</style>
      </a>
    </Link>
  )
}

export default Post

// javascript/rest-sveltekit/src/lib/components/Post.svelte
<script>
  import { marked } from 'marked'

  export let post 

  $: authorName = post.author ? post.author.name : 'Unknown author'
</script>

<a href="/p/{post.id}">
  <article>
    <h2>{post.title}</h2>
    <small>By {authorName}</small>
    {@html marked(post.content)}
  </article>
</a>

<style>
  article {
    color: inherit;
    padding: 2rem;
  }
  a {
    text-decoration: none;
    color: inherit;
  }
</style>
