// javascript/rest-sveltekit/src/routes/p/[id]/+page.svelte
<script>
  import { goto } from '$app/navigation'

  export let data

  const { post } = data

  const deletePost = async () => {
    await (
      await fetch(`/api/post/${post.id}`, {
        method: 'DELETE',
      })
    ).json()
    goto('/')
  }

  const publishPost = async () => {
    await (
      await fetch(`/api/publish/${post.id}`, {
        method: 'PUT',
      })
    ).json()
    goto('/')
  }
</script>

<div class="page">
  <main>
    <h2>{post.title}</h2>
    <p>{post.author?.name ? `By ${post.author.name}` : 'Unknown author'}</p>
    <div>
      {@html post.content}
    </div>
    <div class="actions">
      {#if !post.published}
        <button on:click={publishPost}>Publish</button>
      {/if}
      <button on:click={deletePost}>Delete</button>
    </div>
  </main>
</div>

<style>
  .page {
    background: white;
    padding: 2rem;
  }

  .actions {
    margin-top: 2rem;
  }

  button {
    background: #ececec;
    border: 0;
    border-radius: 0.125rem;
    padding: 1rem 2rem;
  }

  button + button {
    margin-left: 1rem;
  }
</style>

// typescript/rest-nextjs-api-routes/pages/p/[id].tsx
import React from 'react'
import { GetServerSideProps } from 'next'
import ReactMarkdown from 'react-markdown'
import Layout from '../../components/Layout'
import Router from 'next/router'
import { PostProps } from '../../components/Post'

async function publish(id: number): Promise<void> {
  await fetch(`/api/publish/${id}`, {
    method: 'PUT',
  })
  await Router.push('/')
}

async function destroy(id: number): Promise<void> {
  await fetch(`/api/post/${id}`, {
    method: 'DELETE',
  })
  await Router.push('/')
}

const Post: React.FC<PostProps> = props => {
  let title = props.title
  if (!props.published) {
    title = `${title} (Draft)`
  }

  return (
    <Layout>
      <div>
        <h2>{title}</h2>
        <p>By {props?.author?.name || 'Unknown author'}</p>
        <ReactMarkdown children={props.content} />
        {!props.published && (
          <button onClick={() => publish(props.id)}>
            Publish
          </button>
        )}
        <button onClick={() => destroy(props.id)}>
          Delete
        </button>
      </div>
      <style jsx>{`
        .page {
          background: white;
          padding: 2rem;
        }

        .actions {
          margin-top: 2rem;
        }

        button {
          background: #ececec;
          border: 0;
          border-radius: 0.125rem;
          padding: 1rem 2rem;
        }

        button + button {
          margin-left: 1rem;
        }
      `}</style>
    </Layout>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch('http://localhost:3000/api/post/${context.params.id}')
  const data = await res.json()
  return { props: { ...data } }
}

export default Post
