// accelerate/nuxtjs-starter/components/Quote.vue
<template>
	<QuoteWrapper :title="title" :type="type">
		<div class="flex flex-col">
			<p v-if="result?.data" class="text-lg">
				<span class="text-green-300">ID {{ id }}</span> ⸺ '"
				<span v-html="quote"></span>
				"'
			</p>
			<br v-if="result?.data" />
			<p v-if="result?.data" class="text-slate-200 text-lg font-normal text-black ">
				<span class="mt-3.5">Created At</span> ⸺
				{{ formatDate(createdAt) }}
			</p>
			<div v-if="result?.data" class="my-2 h-0.5 border-t-0 bg-neutral-100 opacity-100 dark:opacity-50"></div>
			<div v-if="result?.data">
				<br />
				<p>
					Cache Node Region ⸺
					<span class="font-bold">
						{{ findIATA(region)?.city || region }}
					</span>
				</p>
				<br />
				<p>
					Cached Modified at ⸺
					<span class="font-bold">
						{{ formatDate(lastModified) }}
					</span>
				</p>
				<br />
				<p>
					Cache status ⸺
					<span class="font-bold" :class="{
						'text-green-400': cacheStatus === 'swr' || cacheStatus === 'ttl',
						'text-red-400': cacheStatus !== 'swr' && cacheStatus !== 'ttl'
					}">
						{{ cacheStatus?.toUpperCase() }}
						{{ cacheStatus === 'swr' || cacheStatus === 'ttl'
							? ' CACHE HIT'
							: '' }}
					</span>
				</p>
				<br />
				<p>
					Time taken: <span class="font-bold"> {{ result.time }}ms</span>
				</p>
				<br />
			</div>
			<p v-else class="text-red-500">No data available</p>
		</div>
	</QuoteWrapper>
</template>

<script setup lang="ts">
import { defineProps, computed } from 'vue';
import QuoteWrapper from './QuoteWrapper.vue';
import type { QuoteResult, QuoteCacheType } from '@/lib/types';
import { findIATA } from "openflights-cached";

const props = defineProps<{
	title: string;
	type: QuoteCacheType;
	result: QuoteResult | null;
}>();

const id = computed(() => props.result?.data?.id);
const quote = computed(() => props.result?.data?.quote);
const createdAt = computed(() => props.result?.data?.createdAt || '');
const region = computed(() => props.result?.info?.region || '');
const lastModified = computed(() => props.result?.info?.lastModified || '');
const cacheStatus = computed(() => props.result?.info?.cacheStatus || '');


function formatDate(date: string | undefined) {
	return date ? new Date(date).toLocaleString('en-US') : 'N/A';
}

</script>

// accelerate/remix-starter/app/components/Quote/Quote.tsx
/* eslint-disable react/prop-types */
import { QuoteWrapper } from "./QuoteWrapper";
import { QuoteCacheType, QuoteResult } from "./../../lib/types";
import pkg from "openflights-cached";
const { findIATA } = pkg;

export const Quote: React.FC<{
  title: string;
  type: QuoteCacheType;
  result: QuoteResult;
}> = ({ title, type, result }) => {
  const [{ id, quote, createdAt }, { cacheStatus, region, lastModified }] = [
    result.data,
    result.info,
  ];

  return (
    <QuoteWrapper title={title} type={type}>
      <div className="flex flex-col">
        <p className="text-lg">
          {" "}
          <span className="text-green-300">ID {id} </span>⸺ {'"'}
          {quote}
          {'"'}
        </p>
        <br />
        <p className="text-lg">
          <span className="font-bold mt-3.5">Created At</span> ⸺
          {new Date(createdAt).toLocaleString("en-US")}
        </p>

        <div className="my-2 h-0.5 border-t-0 bg-neutral-100 opacity-100 dark:opacity-50"></div>

        <div>
          <br />
          <p>
            Cache Node Region ⸺
            <span className="font-bold">
              {" "}
              {findIATA(region)?.city ?? region}
            </span>
          </p>
          <br />
          <p>
            Cached Modified at ⸺{" "}
            <span className="font-bold">
              {" "}
              {new Date(lastModified).toLocaleString("en-US")}
            </span>
          </p>
          <br />
          <p>
            Cache status ⸺{" "}
            <span
              className={`font-bold ${
                cacheStatus === "swr" || cacheStatus === "ttl"
                  ? "text-green-400"
                  : "text-red-400"
              }`}
            >
              {" "}
              {cacheStatus
                .toUpperCase()
                .concat(
                  cacheStatus === "swr" || cacheStatus === "ttl"
                    ? " CACHE HIT"
                    : "",
                )}
            </span>
          </p>
          <br />
          <p>
            Time taken: <span className="font-bold"> {result.time}ms</span>
          </p>
          <br />
        </div>
      </div>
    </QuoteWrapper>
  );
};
