// accelerate/svelte-starter/src/components/QuoteWrapper.svelte
<script lang="ts">
  import type { QuoteCacheType } from '../lib/types'

  export let title: string
  export let type: QuoteCacheType
</script>

<div
  class="w-full h-full bg-white border border-gray-200 rounded-lg shadow p-4 dark:bg-gray-800 dark:border-gray-700"
>
  <div class="flex items-center justify-between">
    <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">
      {title}
    </h5>
    <div class="w-16"></div>
    <p class="text-xl font-medium text-blue-600 dark:text-blue-500">{type}</p>
  </div>
  <slot></slot>
</div>

// accelerate/remix-starter/app/components/Quote/QuoteWrapper.tsx
/* eslint-disable react/prop-types */
import { QuoteCacheType } from "../../lib/types";
import { ReactNode } from "react";

export const QuoteWrapper: React.FC<{
  title: string;
  type: QuoteCacheType;
  children: ReactNode;
}> = ({ title, type, children }) => {
  return (
    <div className="w-full h-full bg-white border border-gray-200 rounded-lg shadow p-4 dark:bg-gray-800 dark:border-gray-700">
      <div className="flex items-center justify-between">
        <h5 className="text-xl font-bold leading-none text-gray-900 dark:text-white">
          {title}
        </h5>
        <div className="w-16"></div>
        <p className="text-xl font-medium text-blue-600 dark:text-blue-500">
          {type}
        </p>
      </div>
      <div>{children}</div>
    </div>
  );
};
