// javascript/rest-sveltekit/src/routes/p/[id].svelte
<script>
  import { goto } from '$app/navigation'
  import { marked } from 'marked'

  export let post

  $: authorName = post.author ? post.author.name : 'Unknown author'

  async function publish() {
    await fetch(`/publish/${post.id}`, {
      method: 'PUT',
    })
    await goto('/')
  }

  async function destroy() {
    await fetch(`/p/${post.id}`, {
      method: 'DELETE',
      headers: {
        'accept': 'application/json'
      }
    })
    await goto('/')
  }
</script>

<div class="page">
  <h1>{post.title}{#if !post.published}&nbsp;(Draft){/if}</h1>
  <small>By {authorName}</small>
  {@html marked(post.content)}
  <div class="actions">
    {#if !post.published}
      <button on:click|preventDefault={publish}>Publish</button>
    {/if}
    <button on:click|preventDefault={destroy}>Delete</button>
  </div>
</div>

<style>
  .page {
    background: white;
    padding: 2rem;
  }

  .actions {
    margin-top: 2rem;
  }

  button {
    background: #ececec;
    border: 0;
    border-radius: 0.125rem;
    padding: 1rem 2rem;
  }

  button + button {
    margin-left: 1rem;
  }
</style>

// javascript/rest-nextjs/pages/p/[id].jsx
import ReactMarkdown from 'react-markdown'
import Layout from '../../components/Layout'
import Router from 'next/router'

async function publish(id) {
  await fetch(`/api/publish/${id}`, {
    method: 'PUT',
  })
  await Router.push('/')
}

async function destroy(id) {
  await fetch(`/api/post/${id}`, {
    method: 'DELETE',
  })
  await Router.push('/')
}

const Post = props => {
  let title = props.title
  if (!props.published) {
    title = `${title} (Draft)`
  }
  const authorName = props.author ? props.author.name : 'Unknown author'
  return (
    <Layout>
      <div className="page">
        <h2>{title}</h2>
        <small>By {authorName}</small>
        <ReactMarkdown children={props.content} />
        <div className="actions">
          {!props.published && (
            <button onClick={() => publish(props.id)}>Publish</button>
          )}
          <button onClick={() => destroy(props.id)}>Delete</button>
        </div>
      </div>
      <style jsx>{`
        .page {
          background: white;
          padding: 2rem;
        }

        .actions {
          margin-top: 2rem;
        }

        button {
          background: #ececec;
          border: 0;
          border-radius: 0.125rem;
          padding: 1rem 2rem;
        }

        button + button {
          margin-left: 1rem;
        }
      `}</style>
    </Layout>
  )
}

export const getServerSideProps = async (context) => {
  const res = await fetch(`${location.origin}/api/post/${context.params.id}`)
  const data = await res.json()
  return { props: { ...data } }
}

export default Post
