// typescript/rest-nextjs-api-routes/src/app/drafts/page.tsx
import Post, { PostProps } from '@/components/Post'
import prisma from '@/lib/prisma'
import styles from './page.module.css'

type Props = {
  drafts: PostProps[]
}

export default async function Drafts() {
  const drafts = await prisma.post.findMany({
    where: { published: false },
    include: { author: true },
  })

  return (
    <div>
      <h1>Drafts</h1>
      <main>
        {drafts.map((post) => (
          <div key={post.id} className={styles.post}>
            <Post post={post} />
          </div>
        ))}
      </main>
    </div>
  )
}

// orm/sveltekit/src/routes/drafts/+page.svelte
<script lang="ts">
  import Post from "$lib/components/Post.svelte";
  import type { PageData } from "./$types";

  interface Props {
    data: PageData;
  }

  let { data }: Props = $props();
</script>

<div>
  <h1>Drafts</h1>
  <main>
    <div>
      {#each data.drafts as post (post.id)}
        <Post {post} />
      {/each}
    </div>
  </main>
</div>
