// orm/remix/app/routes/index.tsx
import { json } from '@remix-run/node';
import { useLoaderData } from '@remix-run/react';
import { prisma } from '~/lib/prisma.server'
import Post from '~/components/Post'

export async function loader() {
  const feed = await prisma.post.findMany({
    where: { published: true },
    select: {
      id: true,
      title: true,
      author: true,
    }
  })

  return json({ feed })
}

export default function Index() {
  const { feed } = useLoaderData<typeof loader>()
  return (
    <div className="page">
      <h1>My Blog</h1>
      <main>
        {feed.map((post) => (
          <div key={post.id} className="post">
            <Post post={post} />
          </div>
        ))}
      </main>
    </div>
  );
}

// orm/sveltekit/src/routes/+page.svelte
<script lang="ts">
  import Post from '$lib/components/Post.svelte'
  import type { PageData } from './$types'
  
  
  interface Props {
    // data returned from +page.server.js
    data: PageData;
  }

  let { data }: Props = $props();

</script>

<div>
  <h1>My Blog</h1>
  <main>
    <div>
      {#each data.feed as post (post.id)}
        <Post {post} />
      {/each}
    </div>
  </main>
</div>
