// javascript/rest-nuxtjs/pages/drafts.vue
<template>
  <div class="page">
    <h1>Drafts</h1>
    <main>
      <p v-if="$fetchState.pending">
        <span class="loading"></span>
      </p>
      <p v-else-if="$fetchState.error">Error while fetching drafts 💔</p>
      <div v-else>
        <Post class="post" v-for="post in drafts" :key="post.id" :post="post" />
      </div>
    </main>
  </div>
</template>
<script>
import Post from '@/components/Post'

export default {
  components: { Post },
  data() {
    return {
      drafts: [],
    }
  },
  async fetch() {
    const drafts = await fetch(`http://localhost:3000/api/drafts`).then((res) =>
      res.json()
    )
    this.drafts = drafts
  },
}
</script>
<style scoped>
.post {
  background: white;
  transition: box-shadow 0.1s ease-in;
}

.post:hover {
  box-shadow: 1px 1px 3px #aaa;
}

.post + .post {
  margin-top: 2rem;
}
</style>

// typescript/rest-nextjs-api-routes/pages/drafts.tsx
import React from 'react'
import { GetServerSideProps } from 'next'
import Layout from '../components/Layout'
import Post, { PostProps } from '../components/Post'

type Props = {
  drafts: PostProps[]
}

const Drafts: React.FC<Props> = (props) => {
  return (
    <Layout>
      <div className="page">
        <h1>Drafts</h1>
        <main>
          {props.drafts.map((post) => (
            <div key={post.id} className="post">
              <Post post={post} />
            </div>
          ))}
        </main>
      </div>
      <style jsx>{`
        .post {
          background: white;
          transition: box-shadow 0.1s ease-in;
        }

        .post:hover {
          box-shadow: 1px 1px 3px #aaa;
        }

        .post + .post {
          margin-top: 2rem;
        }
      `}</style>
    </Layout>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('http://localhost:3000/api/drafts')
  const drafts = await res.json()
  return {
    props: { drafts },
  }
}

export default Drafts
